# Generated by Django 4.2.6 on 2023-10-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='research_area',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
