# Generated by Django 4.2.6 on 2023-10-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentor_research_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='research_area',
        ),
        migrations.CreateModel(
            name='ResearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.mentor')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor.research')),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='researches',
            field=models.ManyToManyField(through='mentor.ResearchDetails', to='mentor.research'),
        ),
    ]
