# Generated by Django 4.2.6 on 2023-10-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'completed'), (2, 'not_started'), (3, 'running')], default=2),
        ),
    ]
