# Generated by Django 4.2.6 on 2023-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorship_status_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'accepted'), (3, 'rejected'), (4, 'cancelled')], default=1),
        ),
    ]
