# Generated by Django 4.2.6 on 2023-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_alter_mentorship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'completed'), (2, 'not_started'), (3, 'running'), (4, 'cancelled')], default=2),
        ),
    ]
